FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Define build-time environment variables
ARG REACT_APP_BASE_URL
ARG REACT_APP_URL

# Set the build-time environment variables as actual environment variables in the image
ENV REACT_APP_BASE_URL=$REACT_APP_BASE_URL
ENV REACT_APP_URL=$REACT_APP_URL
ENV PORT=1000

# Copy the package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

# Expose the port `serve` runs on
EXPOSE 1000

# Command to run the app
CMD ["npm", "run", "start"]
