version: "3.8"

services:
  admin:
    build:
      context: ./Admin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  react:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
        - REACT_APP_URL=${REACT_APP_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env

networks:
  default:
    driver: bridge
