version: "3.8"

services:
  fastapi-app:
    build:
      context: ./Backend
      dockerfile: Dockerfile.development
    ports:
      - "8000:8000"
    environment:
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ./Backend:/Backend
    depends_on:
      - db

  react-app:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.development
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BASE_URL="http://127.0.0.1:8000"
    volumes:
      - ./Frontend:/Frontend
    depends_on:
      - fastapi-app

  django-app:
    build: 
      context: ./Admin
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
    environment:
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - db
    volumes:
      - ./Admin:/Admin

  db:
    image: mysql:5.7
    ports:
      - "4000:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  Backend:
  Frontend:
  DjangoApp:
  mysql-data:

