version: "3.8"

services:
  fastapi-app:
    build: ./Backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ./Backend:/Backend
    depends_on:
      - db
    networks:
      corux:
        ipv4_address: 10.1.1.2

  react-app:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BASE_URL="http://127.0.0.1:8000"
    volumes:
      - ./Frontend:/Frontend
    depends_on:
      - fastapi-app
    networks:
      corux:
        ipv4_address: 10.1.1.3

  django-app:
    build: ./Admin
    ports:
      - "8080:8080"
    environment:
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - db
    volumes:
      - ./Admin:/Admin
    networks:
      corux:
        ipv4_address: 10.1.1.4

  db:
    image: mysql:5.7
    ports:
      - "4000:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      corux:
        ipv4_address: 10.1.1.5

volumes:
  Backend:
  Frontend:
  DjangoApp:
  mysql-data:

networks:
  corux:
    driver: bridge
    ipam:
      config:
      - subnet: 10.1.1.0/24
