# Generated by Django 4.2.11 on 2024-04-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_paymenttable_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDepositTable',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MOBILE_NUMBER', models.CharField(max_length=15)),
                ('USER_UPI_ID', models.CharField(max_length=50)),
                ('ADMIN_UPI_ID', models.CharField(max_length=50, null=True)),
                ('UTR', models.CharField(max_length=50, null=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
                ('AMOUNT', models.FloatField()),
                ('APPROVE_DEPOSIT', models.BooleanField(default=False)),
                ('DENY_DEPOSIT', models.BooleanField(default=False)),
                ('UPDATE_DATE', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'DEPOSIT',
            },
        ),
        migrations.CreateModel(
            name='PaymentWithdrawTable',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MOBILE_NUMBER', models.CharField(max_length=15)),
                ('UTR', models.CharField(max_length=50, null=True)),
                ('USER_UPI_ID', models.CharField(max_length=50)),
                ('ADMIN_UPI_ID', models.CharField(max_length=50, null=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
                ('AMOUNT', models.FloatField()),
                ('APPROVE_WITHDRAW', models.BooleanField(default=False)),
                ('DENY_WITHDRAW', models.BooleanField(default=False)),
                ('UPDATE_DATE', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'WITHDRAW',
            },
        ),
        migrations.DeleteModel(
            name='PaymentTable',
        ),
    ]
