# Generated by Django 4.2.11 on 2024-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_paymentdeposittable_paymentwithdrawtable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdeposittable',
            name='ADMIN_UPI_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdeposittable',
            name='UPDATE_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdeposittable',
            name='UTR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentwithdrawtable',
            name='ADMIN_UPI_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentwithdrawtable',
            name='UPDATE_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentwithdrawtable',
            name='UTR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
