# Generated by Django 4.2.11 on 2024-04-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_paymentdeposittable_admin_upi_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpiTable',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('USER_NAME', models.CharField(max_length=30)),
                ('UPI_ID', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ADMIN_UPI',
            },
        ),
    ]
