# Generated by Django 4.2.11 on 2024-04-18 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_upitable'),
    ]

    operations = [
        migrations.AddField(
            model_name='upitable',
            name='CREATE_DATE',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upitable',
            name='UPDATE_DATE',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
